---
title: "Project"
author: "Ruoqing Jiang"
date: "2016Äê5ÔÂ29ÈÕ"
output: html_document
---



map = read.table("E:/nyt_eng_200812.map", quote="")
map[inds[1:100,],2]
```{r}
library(Matrix)

inds = read.table("E:/nyt_eng_200812 (4).ind")
inds2=simplify2array(inds)
```
```{r}
test<-inds2[1:50000]
n<-length(test)-1
l<-length(unique(test))

IJ = matrix(0, n, 2)

for (i in 1:n) {
  IJ[i,] = test[i:(i+1)]
}
IJ = unique(IJ)
idxlookup = sparseMatrix(i = IJ[,1], j = IJ[,2], x=seq(1, dim(IJ)[1]), dims = c(l, l))

npairs = dim(IJ)[1]

nfrequency = rep(0, npairs)
for(i in 1:n) {
  w1 = test[i]
  w2 = test[i+1]
  idx = idxlookup[w1, w2]
  nfrequency[idx] = nfrequency[idx] + 1
}
nfrequency[1:10]
```

```{r}
frequency<-rep(0,l)
for(i in 1:n) {
frequency[test[i]] = frequency[test[i]]+1
}

conditional= rep(0, npairs)
for(i in 1:npairs) {
  w1 = IJ[i,1]
  w2 = IJ[i,2]
  idx = idxlookup[w1, w2]
  conditional[idx] = nfrequency[idx]/frequency[w1]
}
conditional[1:10]
```

```{r}
draw.sample<-function(conditional,l,size) {
  new<-rep(0,size)
  new[1]<-1

  for(i in 2:size) {
    p<-conditional[idxlookup[new[i-1],]]
    x<-which(idxlookup[new[i-1],] > 0, arr.ind = T)
    
    idx = sample.int(length(p), size = 1, prob=p)
    new[i] = x[idx]
  }
  return(new)
}

newsample<-draw.sample(conditional,l,10000)
newsample[1:100]
```

```
PMI<-function(s,l,idxlookup,npairs) {
n<-length(s)-1
nfrequency = rep(0, npairs)
for(i in 1:n) {
  w1 = s[i]
  w2 = s[i+1]
  idx = idxlookup[w1, w2]
  nfrequency[idx] = nfrequency[idx] + 1
}
nprob<-nfrequency/(length(s)-1)

frequency<-rep(0,l)
for(i in 1:n) {
frequency[s[i]] = frequency[s[i]]+1
}
prob<-frequency/length(s)

pmi= rep(0, npairs)
for(i in 1:n) {
  w1 = s[i]
  w2 = s[i+1]
  idx = idxlookup[w1, w2]
  if ((prob[w1]!=0)&&(prob[w2]!=0)) {
    pmi[idx] = nprob[idx]/(prob[w1]*prob[w2])
  }
}  
return (pmi)
}
```

```
result<-PMI(newsample,l,idxlookup,npairs)
result[1:100]
```